// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFs1Qg4-N4tpswxum2hZf5yQM41DTloLA',
    appId: '1:782758238451:web:636179fe408bc12036bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    authDomain: 'smart-accident-system.firebaseapp.com',
    databaseURL: 'https://smart-accident-system-default-rtdb.firebaseio.com',
    storageBucket: 'smart-accident-system.firebasestorage.app',
    measurementId: 'G-8KXD8YJR18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevzjss4WUBVoBo3oiivM9avt27pjJcbk',
    appId: '1:782758238451:android:4a912d67a4352e0736bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    databaseURL: 'https://smart-accident-system-default-rtdb.firebaseio.com',
    storageBucket: 'smart-accident-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF7LvVAro1UwcSshVsle67FjlqyMXkZ4A',
    appId: '1:782758238451:ios:bda6b5e123e07ed836bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    databaseURL: 'https://smart-accident-system-default-rtdb.firebaseio.com',
    storageBucket: 'smart-accident-system.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF7LvVAro1UwcSshVsle67FjlqyMXkZ4A',
    appId: '1:782758238451:ios:bda6b5e123e07ed836bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    databaseURL: 'https://smart-accident-system-default-rtdb.firebaseio.com',
    storageBucket: 'smart-accident-system.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdrCr35SiXnTS2QU0rB49mC4nv7aSGCP4',
    appId: '1:782758238451:web:fbe7a99e76422ef936bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    authDomain: 'smart-accident-system.firebaseapp.com',
    databaseURL: 'https://smart-accident-system-default-rtdb.firebaseio.com',
    storageBucket: 'smart-accident-system.firebasestorage.app',
    measurementId: 'G-HQM2CS1JN7',
  );
}
